name: Build WPF (.NET 8)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore .\src\InjazAcc.UI\InjazAcc.UI.csproj

      - name: Build (Release)
        run: dotnet build .\src\InjazAcc.UI\InjazAcc.UI.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish .\src\InjazAcc.UI\InjazAcc.UI.csproj -c Release -o .\publish\InjazAcc.UI

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: InjazAcc.UI-Release
          path: publish/InjazAcc.UI/**
