name: Release on tag

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore .\src\InjazAcc.UI\InjazAcc.UI.csproj

      - name: Publish (win-x64)
        run: dotnet publish .\src\InjazAcc.UI\InjazAcc.UI.csproj -c Release -r win-x64 --self-contained false -o .\publish\InjazAcc.UI

      - name: Zip artifact
        run: Compress-Archive -Path .\publish\InjazAcc.UI\* -DestinationPath .\InjazAcc_win-x64.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: InjazAcc_win-x64.zip
